export const timeZonesByCountry = {
  Pakistan: [
    "Asia/Karachi",
    "Asia/Lahore",
    "Asia/Islamabad",
    "Asia/Peshawar",
    "Asia/Quetta",
  ],
  "South Asia": {
    India: [
      "Asia/Kolkata",
      "Asia/Mumbai",
      "Asia/Delhi",
      "Asia/Bangalore",
      "Asia/Chennai",
    ],
    Bangladesh: ["Asia/Dhaka"],
    "Sri Lanka": ["Asia/Colombo"],
    Nepal: ["Asia/Kathmandu"],
    Bhutan: ["Asia/Thimphu"],
    Maldives: ["Indian/Maldives"],
  },
  "Middle East": {
    UAE: ["Asia/Dubai", "Asia/Abu_Dhabi"],
    "Saudi Arabia": ["Asia/Riyadh", "Asia/Jeddah", "Asia/Dammam"],
    Iran: ["Asia/Tehran"],
    Iraq: ["Asia/Baghdad"],
    Kuwait: ["Asia/Kuwait"],
    Bahrain: ["Asia/Bahrain"],
    Qatar: ["Asia/Qatar"],
    Oman: ["Asia/Muscat"],
    Yemen: ["Asia/Aden"],
    Jordan: ["Asia/Amman"],
    Lebanon: ["Asia/Beirut"],
    Syria: ["Asia/Damascus"],
  },
  "East Asia": {
    China: ["Asia/Shanghai", "Asia/Beijing", "Asia/Hong_Kong", "Asia/Macau"],
    Japan: ["Asia/Tokyo", "Asia/Osaka"],
    "South Korea": ["Asia/Seoul"],
    "North Korea": ["Asia/Pyongyang"],
    Taiwan: ["Asia/Taipei"],
    Mongolia: ["Asia/Ulaanbaatar"],
  },
  "Southeast Asia": {
    Singapore: ["Asia/Singapore"],
    Malaysia: ["Asia/Kuala_Lumpur"],
    Indonesia: ["Asia/Jakarta", "Asia/Bali"],
    Thailand: ["Asia/Bangkok"],
    Vietnam: ["Asia/Ho_Chi_Minh", "Asia/Hanoi"],
    Philippines: ["Asia/Manila"],
    Myanmar: ["Asia/Yangon"],
    Cambodia: ["Asia/Phnom_Penh"],
    Laos: ["Asia/Vientiane"],
    Brunei: ["Asia/Brunei"],
  },
  "Central Asia": {
    Afghanistan: ["Asia/Kabul"],
    Kazakhstan: ["Asia/Almaty", "Asia/Nur-Sultan"],
    Uzbekistan: ["Asia/Tashkent"],
    Turkmenistan: ["Asia/Ashgabat"],
    Kyrgyzstan: ["Asia/Bishkek"],
    Tajikistan: ["Asia/Dushanbe"],
  },
  Europe: {
    UK: ["Europe/London", "Europe/Belfast", "Europe/Edinburgh"],
    Germany: ["Europe/Berlin", "Europe/Munich"],
    France: ["Europe/Paris"],
    Italy: ["Europe/Rome", "Europe/Vatican"],
    Spain: ["Europe/Madrid", "Europe/Barcelona"],
    Portugal: ["Europe/Lisbon"],
    Netherlands: ["Europe/Amsterdam"],
    Belgium: ["Europe/Brussels"],
    Switzerland: ["Europe/Zurich"],
    Austria: ["Europe/Vienna"],
    Sweden: ["Europe/Stockholm"],
    Norway: ["Europe/Oslo"],
    Denmark: ["Europe/Copenhagen"],
    Finland: ["Europe/Helsinki"],
    Ireland: ["Europe/Dublin"],
    Poland: ["Europe/Warsaw"],
    Russia: ["Europe/Moscow", "Asia/Vladivostok", "Asia/Novosibirsk"],
    Ukraine: ["Europe/Kiev"],
    Greece: ["Europe/Athens"],
    Turkey: ["Europe/Istanbul"],
  },
  "North America": {
    USA: [
      "America/New_York",
      "America/Chicago",
      "America/Los_Angeles",
      "America/Denver",
      "Pacific/Honolulu",
      "America/Anchorage",
    ],
    Canada: [
      "America/Toronto",
      "America/Vancouver",
      "America/Montreal",
      "America/Edmonton",
    ],
    Mexico: ["America/Mexico_City", "America/Cancun"],
  },
  "Central America": {
    Panama: ["America/Panama"],
    "Costa Rica": ["America/Costa_Rica"],
    Guatemala: ["America/Guatemala"],
    Honduras: ["America/Tegucigalpa"],
    "El Salvador": ["America/El_Salvador"],
    Nicaragua: ["America/Managua"],
    Belize: ["America/Belize"],
  },
  "South America": {
    Brazil: ["America/Sao_Paulo", "America/Rio_de_Janeiro"],
    Argentina: ["America/Buenos_Aires"],
    Chile: ["America/Santiago"],
    Colombia: ["America/Bogota"],
    Peru: ["America/Lima"],
    Venezuela: ["America/Caracas"],
    Ecuador: ["America/Guayaquil"],
    Bolivia: ["America/La_Paz"],
    Paraguay: ["America/Asuncion"],
    Uruguay: ["America/Montevideo"],
  },
  Oceania: {
    Australia: [
      "Australia/Sydney",
      "Australia/Melbourne",
      "Australia/Brisbane",
      "Australia/Perth",
      "Australia/Adelaide",
    ],
    "New Zealand": ["Pacific/Auckland", "Pacific/Wellington"],
    Fiji: ["Pacific/Fiji"],
    "Papua New Guinea": ["Pacific/Port_Moresby"],
    "Solomon Islands": ["Pacific/Guadalcanal"],
    "New Caledonia": ["Pacific/Noumea"],
  },
  Africa: {
    "South Africa": ["Africa/Johannesburg"],
    Egypt: ["Africa/Cairo"],
    Morocco: ["Africa/Casablanca"],
    Kenya: ["Africa/Nairobi"],
    Nigeria: ["Africa/Lagos"],
    Ethiopia: ["Africa/Addis_Ababa"],
    Tanzania: ["Africa/Dar_es_Salaam"],
    Ghana: ["Africa/Accra"],
    Uganda: ["Africa/Kampala"],
    Algeria: ["Africa/Algiers"],
    Sudan: ["Africa/Khartoum"],
    Libya: ["Africa/Tripoli"],
    Tunisia: ["Africa/Tunis"],
  },
};
